# reset config
# curl -Lo ~/.tmux/reset --create-dirs https://raw.githubusercontent.com/hallazzang/tmux-reset/3.0/tmux-reset
source-file ~/.tmux/reset

# general options
set -g default-terminal "xterm-256color"
set -sg escape-time 0
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse off
set -sg base-index 1
set -wg pane-base-index 1

set -g set-clipboard off

# statusline
set -g status-left "#[fg=#2c3efb,bg=#ffffff][#{session_name}]#[default] "
set -g status-right "#[fg=#ffffff,bg=#ff453a] %Y-%m-%d %H:%M #[default]"
set -g status-right-length 50

set -ag status-style "bg=#ffffff"
set -ag status-style "fg=#2c3efb"

set -g window-status-current-format ''
set -g window-status-format ''
   
set -ag window-status-format " #{window_index} #{window_name} #{?#{>:#{window_panes},1},-,} "
set -ag window-status-current-format " #{window_index} #{window_name} * "

set -ag window-status-style "bg=#767dfd"
set -ag window-status-style "fg=#ffffff"
set -ag window-status-current-style "bg=#2c3efb"
set -ag window-status-current-style "fg=#ffffff"

set -g pane-active-border-style "fg=#2c3efb"

# bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# use <C-b>g and <C-b>v to split windows
unbind %
unbind '"'
bind v split-window -h -c "#{pane_current_path}"
bind g split-window -v -c "#{pane_current_path}"

bind R source-file ~/.tmux.conf \; display-message "Config reloaded..."
